### ISSUE TITLE
Prototipagem da tela de cadastro de empresa

### ISSUE THREAD

**Issue by EnhoDragneel** [ES2-UFPI/TalentSpotAI#14]
Criação de um protótipo visual da interface de cadastro de novas empresas. Este protótipo deve especificar todos os campos necessários, como nome, CNPJ, endereço e outros detalhes importantes, além de botões e orientações ao usuário.

**Comment by luishenriqueom** [comment]
Mudança: agora o mesmo formulário, no caso, os campos, serão os mesmos tanto para o candidato quanto para o gestor/recrutador
