### ISSUE TITLE
Prototipagem da tela de listagem de empresas

### ISSUE THREAD

**Issue by EnhoDragneel** [ES2-UFPI/TalentSpotAI#16]
Desenvolvimento de um modelo interativo para a tela onde serão listadas todas as empresas cadastradas. A prototipagem deve contemplar funcionalidades como busca, filtros, e visualização de informações principais de cada empresa para facilitar a gestão.

**Comment by luishenriqueom** [comment]
OK
![image](https://github.com/user-attachments/assets/ac661007-51f1-485e-91f1-c35272041748)
