### ISSUE TITLE
Prototipagem da Tela de Listagem de Currículos 

### ISSUE THREAD

**Issue by EnhoDragneel** [ES2-UFPI/TalentSpotAI#21]
Desenvolvimento de um protótipo interativo para a tela onde serão listados todos os currículos cadastrados. A prototipagem deve incluir funcionalidades como busca, filtros, e visualização das informações principais de cada currículo para facilitar a gestão.

**Comment by EnhoDragneel** [comment]
Ainda não enviei o código pois está nas fases de testes, mas segue aqui o protótipo de como está ficando:


Configuração do Servidor:

const express = require('express');
const bodyParser = require('body-parser');
const path = require('path');
const db = require('./database');

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(bodyParser.urlencoded({ extended: true }));
app.use(express.static(path.join(__dirname, 'public')));

// Rota para servir o formulário
app.get('/', (req, res) => {
    res.sendFile(path.join(__dirname, 'public/index.html'));
});

// Rota para processar o formulário
app.post('/submit', (req, res) => {
    const { nome, email, mensagem } = req.body;
    db.run('INSERT INTO submissions (nome, email, mensagem) VALUES (?, ?, ?)', [nome, email, mensagem], (err) => {
        if (err) {
            return res.status(500).send('Erro ao salvar os dados!');
        }
        res.send('Dados enviados com sucesso!');
    });
});

// Inicializa o servidor
app.listen(PORT, () => {
    console.log(`Servidor rodando na porta ${PORT}`);
});


Configuração do Banco de Dados

const sqlite3 = require('sqlite3').verbose();
const db = new sqlite3.Database(':memory:');

db.serialize(() => {
    db.run('CREATE TABLE submissions (id INTEGER PRIMARY KEY AUTOINCREMENT, nome TEXT, email TEXT, mensagem TEXT)');
});

module.exports = db;

**Comment by EnhoDragneel** [comment]
![Image](https://github.com/user-attachments/assets/d22fac76-eebb-4f4c-af8e-68e265b36f3b)

**Comment by luishenriqueom** [comment]
Ok.
