### ISSUE TITLE
Prototipagem da tela de atualização de cadastro de candidato

### ISSUE THREAD

**Issue by Th4yss4** [ES2-UFPI/TalentSpotAI#27]
Desenvolvimento de um protótipo interativo para a tela de atualização de cadastro de candidatos. Esta prototipagem deve incluir todos os campos que podem ser editados, botões de ação, visando facilitar a atualização dos dados.

**Comment by luishenriqueom** [comment]
OK
![localhost_3000_perfil](https://github.com/user-attachments/assets/d8e43b28-80f1-40e1-8e93-47de2675385a)
