### ISSUE TITLE
Prototipagem da tela de listagem de vaga de emprego

### ISSUE THREAD

**Issue by EnhoDragneel** [ES2-UFPI/TalentSpotAI#5]
Desenvolvimento de um protótipo interativo para a tela onde serão listadas todas as vagas de emprego cadastradas. A prototipagem deve incluir funcionalidades como busca e visualização das informações principais de cada vaga para facilitar a gestão.

**Comment by luishenriqueom** [comment]
OK
![localhost_3000_perfil](https://github.com/user-attachments/assets/e6710b70-2b9b-45b0-ab36-14d8959c5c69)
