### ISSUE TITLE
Prototipagem da tela de cadastro de candidato

### ISSUE THREAD

**Issue by EnhoDragneel** [ES2-UFPI/TalentSpotAI#9]
Protótipo de tela, feito no Figma, relacionado a tela de cadastro do candidato de modo a ter todas as funcionalidades desejadas, como por exemplo para coleta de dados, para está realizando esse cadastro.

**Comment by luishenriqueom** [comment]
OK
![Image](https://github.com/user-attachments/assets/b4190ebe-902c-4ca5-a532-e77a6863e6a9)
